name: realwear_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lepsi_rw_speech_recognizer: ^2.0.0
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  path: ^1.9.0
  go_router: ^14.6.2
  permission_handler: ^11.3.1
  agora_rtc_engine: ^6.5.1
  screenshot: ^3.0.0
  uuid: ^4.5.1
  fluttertoast: ^8.2.10
  socket_io_client: ^3.0.2
  shared_preferences: ^2.3.2
  logger: ^2.5.0
  badges: ^3.1.2
  loader_overlay: ^4.0.4+1
  cryptography: ^2.7.0
  flutter_screen_recording: ^2.0.24
  wakelock_plus: ^1.3.2
  flutter_dotenv: ^6.0.0
  flutter_webrtc: ^1.2.0

dependency_overrides:
  js: ^0.7.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
